# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='imagens')),
                ('idnoticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Noticias')),
            ],
        ),
    ]
